// <auto-generated />
namespace Cash4Aff.Infra.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adsad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adsad));
        
        string IMigrationMetadata.Id
        {
            get { return "202101191259082_adsad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
