// <auto-generated />
namespace Cash4Aff.Presentation.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edituser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edituser));
        
        string IMigrationMetadata.Id
        {
            get { return "202006060241515_edit-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
