// <auto-generated />
namespace Cash4Aff.Presentation.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sdasdj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sdasdj));
        
        string IMigrationMetadata.Id
        {
            get { return "202009291414573_sdasdj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
