// <auto-generated />
namespace Cash4Aff.Presentation.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addlink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlink));
        
        string IMigrationMetadata.Id
        {
            get { return "202009221647397_addlink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
